[rule]
id = "module-init-test"
description = "Test module init for name 'lkm' and cmd 'insmod'"
type = "module_init"
category = "test"
severity = "high"

[[rule.conditions]]
field = "module_name"
op = "equals"
value = "lkm"

[[rule.conditions]]
field = "comm"
op = "equals"
value = "insmod"
